[package]
name = "dirwalk-comp"
version = "0.1.0"
edition = "2021"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }

[dependencies]
ignore = "0.4.23"
jwalk = "0.8.1"
rayon = "1.10.0"
walkdir = "2.5.0"
